spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testDB
    username: postgres
    password: sdfanc552
  jpa:
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update


app:
  secret-key: 462D4A404E635266556A586E3272357538782F413F4428472B4B625064536756